export const PLATFORMS_CONFIG = [
  {
    value: 'leetcode',
    label: 'LeetCode',
    color: 'from-orange-500 to-orange-600',
    placeholder: 'leetcode_username',
    icon: '/Images/Icons/leetcode.png',
    backendKey: 'leetCodeUsername',
    category: 'DSA',
    getProfileUrl: (username) => `https://leetcode.com/${username}`,
    getDashboardUrl: (displayName) => `/dashboard/${displayName}/coding-profiles/leetcode`,
  },
  {
    value: 'github',
    label: 'GitHub',
    color: 'from-gray-700 to-gray-900',
    placeholder: 'github_username',
    icon: '/Images/Icons/github.png',
    backendKey: 'githubUsername',
    category: 'Development',
    getProfileUrl: (username) => `https://github.com/${username}`,
    getDashboardUrl: (displayName) => `/dashboard/${displayName}/github`,
  },
  {
    value: 'gfg',
    label: 'GeeksForGeeks',
    color: 'from-green-500 to-green-600',
    placeholder: 'geeksforgeeks_username',
    icon: '/Images/Icons/gfg.png',
    backendKey: 'gfgUsername',
    category: 'DSA',
    getProfileUrl: (username) => `https://auth.geeksforgeeks.org/user/${username}`,
    getDashboardUrl: (displayName) => `/dashboard/${displayName}/coding-profiles/gfg`,
  },
  {
    value: 'hackerrank',
    label: 'HackerRank',
    color: 'from-green-400 to-green-500',
    placeholder: 'hackerrank_username',
    icon: '/Images/Icons/hackerrank.png',
    backendKey: 'hackerrankUsername',
    category: 'DSA',
    getProfileUrl: (username) => `https://www.hackerrank.com/${username}`,
    getDashboardUrl: (displayName) => `/dashboard/${displayName}/coding-profiles/hackerrank`,
  },
  {
    value: 'codechef',
    label: 'CodeChef',
    color: 'from-yellow-600 to-yellow-700',
    placeholder: 'codechef_username',
    icon: '/Images/Icons/codechef.png',
    backendKey: 'codechefUsername',
    category: 'DSA',
    getProfileUrl: (username) => `https://www.codechef.com/users/${username}`,
    getDashboardUrl: (displayName) => `/dashboard/${displayName}/coding-profiles/codechef`,
  },
  {
    value: 'code360',
    label: 'Code360',
    color: 'from-blue-700 to-blue-900',
    placeholder: 'code360_username',
    icon: '/Images/Icons/code360.png',
    backendKey: 'code360Username',
    category: 'DSA',
    getProfileUrl: (username) => `https://www.naukri.com/code360/profile/${username}`,
    getDashboardUrl: (displayName) => `/dashboard/${displayName}/coding-profiles/code360`,
  },
  {
    value: 'interviewbit',
    label: 'InterviewBit',
    color: 'from-blue-700 to-blue-900',
    placeholder: 'interviewbit_username',
    icon: '/Images/Icons/interviewbit.png',
    backendKey: 'interviewbitUsername',
    category: 'DSA',
    getProfileUrl: (username) => `https://www.interviewbit.com/profile/${username}`,
    getDashboardUrl: (displayName) => `/dashboard/${displayName}/coding-profiles/interviewbit`,
  },
];

export const HACKERRANK_ICONS = {
  'Problem Solving': 'https://hrcdn.net/fcore/assets/badges/problem-solving-ecaf59a612.svg',
  'C++': 'https://hrcdn.net/fcore/assets/badges/cpp-739b350881.svg',
  Java: 'https://hrcdn.net/fcore/assets/badges/java-9d05b1f559.svg',
  Python: 'https://hrcdn.net/fcore/assets/badges/python-f70befd824.svg',
  '30 Days of Code': 'https://hrcdn.net/fcore/assets/badges/30-days-of-code-a772ae4c2f.svg',
  '10 Days of JS': 'https://hrcdn.net/fcore/assets/badges/10-days-of-javascript-94ff22d1c9.svg',
  '10 Days of Statistics': 'https://hrcdn.net/fcore/assets/badges/10-days-of-statistics-94ff22d1c9.svg',
  Sql: 'https://hrcdn.net/fcore/assets/badges/sql-89e76e7082.svg',
  C: 'https://hrcdn.net/fcore/assets/badges/c-d1985901e6.svg',
  Ruby: 'https://hrcdn.net/fcore/assets/badges/ruby-b2c8eababe.svg',
  default: '/Images/Default/badge.png',
};
